import '../../di/injection_container.dart';
import 'pref_helper.dart';

PrefHelper? prefHelper = sl();

const String KEY_FCM_ID = "KEY_FCM_ID";
const String KEY_DEVICE_ID = "KEY_DEVICE_ID";
const String KEY_NAME = "KEY_NAME";
const String KEY_NAME_EN = "KEY_NAME_EN";
const String KEY_NAME_AR = "KEY_NAME_AR";

const String KEY_COUNTRY_CODE = "KEY_COUNTRY_CODE";
const String KEY_DEVICE_TOKEN = "KEY_DEVICE_TOKEN";
const String KEY_MOBILE_NO = "KEY_MOBILE_NO";
const String KEY_EMAIL = "KEY_EMAIL";
const String KEY_COUNTRY_NAME = "KEY_COUNTRY_NAME";
const String KEY_CITY_NAME = "KEY_CITY_NAME";
const String KEY_MEMBER_TYPE = "KEY_MEMBER_TYPE";
const String KEY_ALL_MEMBER_TYPE = "KEY_ALL_MEMBER_TYPE";

const String KEY_PASSWORD = "KEY_PASSWORD";
const String KEY_AUTHENTICATION_TOKEN = "KEY_AUTHENTICATION_TOKEN";
const String KEY_NAT_ID = "KEY_NAT_ID";
const String KEY_LANG = "KEY_LANG";
const String KEY_USER_LOGGED_IN = "KEY_USER_LOGGED_IN";
const String KEY_PROFILE_PIC = "KEY_PROFILE_PIC";
const String KEY_APP_THEME = "KEY_APP_THEME";
//Is biometric on device supported or not
const String KEY_IS_BIOMETRIC_AVAILABLE = "KEY_BIOMETRIC_AVAILABLE";
//it is used to check whether user has enabled biometric or not
const String KEY_IS_BIOMETRIC_ENABLED = "KEY_IS_BIOMETRIC_ENABLED";
const String KEY_OTP = "KEY_OTP";
const String KEY_PHONE_NUMBER = "KEY_PHONE_NUMBER";

const String KEY_CONTACT_TYPE = 'KEY_CONTACT_TYPE';
const String KEY_THEME_COLOR = 'KEY_THEME_COLOR';
const String KEY_IS_GUEST_MEMBER = 'KEY_IS_GUEST_MEMBER';
const String KEY_SHOW_GUEST_NOTIFICATIONS = 'KEY_SHOW_GUEST_NOTIFICATIONS';
const String KEY_NOTIFICATION_SUBSCRIPTION_TOPIC =
    "KEY_NOTIFICATION_SUBSCRIPTION_TOPIC";
const String KEY_MEMBER_LIST = 'KEY_MEMBER_LIST';
const String LAST_DASHBOARD_API_CALLED_TIME = 'LAST_DASHBOARD_API_CALLED_TIME';

const String DASHBOARD_NOTIFICATION_ID = 'DASHBOARD_NOTIFICATION_ID';

const String KEY_IS_DARK_THEME = 'KEY_IS_DARK_THEME';
const String KEY_THEME_SYSTEM = 'KEY_THEME_SYSTEM';
const String ANDROID_VERSION = 'ANDROID_VERSION';
const String IOS_VERSION = 'IOS_VERSION';
const String KEY_DASHBOARD_ACTIVE_CARDS = 'KEY_ACTIVE_CARDS';
const String KEY_DASHBOARD_ARCHIVE_CARDS = 'KEY_ARCHIVE_CARDS';
const String KEY_DASHBOARD_ISCARDS = 'KEY_IS_CARDS';
const String KEY_IS_DEDUCTION = "KEY_IS_DEDUCTION";
const String KEY_TIME_STAMP_NOTIFICATION = "KEY_NOTIFICATION_TIME_STAMP";
const String KEY_IS_BIOMETRIC_SHOWN = "KEY_IS_BIOMETRIC_SHOWN";
const String KEY_FETCH_LOGIN_NOTIFICATIONS = "KEY_IS_LOGIN_NOTIFICATION";
const String LAST_APP_UPDATE_CALLED_TIME = 'LAST_APP_UPDATE_CALLED_TIME';
const String SHOULD_SHOW_APP_UPDATE_DIALOG = 'SHOULD_SHOW_APP_UPDATE_DIALOG';
const String TEXT_HEIGHT_KEY = 'TEXT_HEIGHT_KEY';
const String KEY_CERTIFICATE_REQUEST = 'KEY_CERTIFICATE_REQUEST';
const String KEY_PAYMENT_AND_DEDUCTION = 'KEY_PAYMENT_AND_DEDUCTION';
const String KEY_GUEST_DASHBOARD_NOTIFICATION_TIME_STAMP =
    'KEY_GUEST_DASHBOARD_NOTIFICATION_TIME_STAMP';
const String KEY_APP_OPEN_FIRST_TIME = 'KEY_APP_OPEN_FIRST_TIME';
const String KEY_SHOULD_CALL_DASHBOARD_CARDS =
    'KEY_SHOULD_CALL_DASHBOARD_CARDS';
const String KEY_IS_NOTIFICATION_SUBSCRIBED = 'KEY_IS_NOTIFICATION_SUBSCRIBED';
const String KEY_IS_ALIVE = 'KEY_IS_ALIVE';
const String KEY_ALIVE_MESSAGE = 'KEY_ALIVE_MESSAGE';
const String KEY_NEXT_ANNUAL_DECLARATION_DUE =
    'KEY_NEXT_ANNUAL_DECLARATION_DUE';
const String KEY_IS_SUBMIT_LATTER_DIALOG_SHOWN =
    'KEY_IS_SUBMIT_LATTER_DIALOG_SHOWN';
const String KEY_IS_USER_LOGOUT_FROM_MORE = 'KEY_IS_USER_LOGOUT_FROM_MORE';
const String KEY_PREVIOUS_ACTIVE_CARDS = 'KEY_PREVIOUS_ACTIVE_CARDS';
const String KEY_IS_LOGIN_FLOW = 'KEY_IS_LOGIN_FLOW';
const String KEY_MEMBER_DETAILS = 'KEY_MEMBER_DETAILS';
const String KEY_UNREAD_MEMBER_COUNT = 'KEY_UNREAD_MEMBER_COUNT';
const String KEY_UNREAD_TRANSACTION_COUNT = 'KEY_UNREAD_TRANSACTION_COUNT';
const String KEY_LAST_RECEIVED_NOTIFICATION = 'KEY_LAST_RECEIVED_NOTIFICATION';
const String KEY_EMP_ID = 'KEY_EMP_ID';
const String KEY_USER_DATA = 'KEY_USER_DATA';
const String KEY_NEXT_ANNUAL_DECLARATION_DATE =
    'KEY_NEXT_ANNUAL_DECLARATION_DATE';
const String KEY_ANNUAL_CURRENT_DATE_STAMP = 'KEY_ANNUAL_CURRENT_DATE_STAMP';
const String KEY_SHOW_ADD_PS = 'KEY_SHOW_ADD_PS';
const String KEY_SHOULD_LOGOUT = 'KEY_SHOULD_LOGOUT';
const String KEY_ADD_PS_MODIFY_REASON = 'KEY_ADD_PS_MODIFY_REASON';
const String KEY_IS_HAUWEI_PHONE = 'KEY_IS_HAUWEI_PHONE';
const String KEY_SPLASH_FILE_PATH = 'KEY_SPLASH_FILE_PATH';
const String KEY_SPLASH_IMAGE_SECONDS = 'KEY_SPLASH_IMAGE_SECONDS';
const String KEY_SPLASH_VERSION = 'KEY_SPLASH_VERSION';
const String KEY_NEW_SPLASH_IMAGE_SECONDS = 'KEY_NEW_SPLASH_IMAGE_SECONDS';
const String KEY_NEW_SPLASH_VERSION = 'KEY_NEW_SPLASH_VERSION';
const String KEY_NOTIFICATION_PAYLOAD = 'KEY_NOTIFICATION_PAYLOAD';
